Plugin created a page with a component that doesn't exist
This is likely due to the fact that most starters and sites use
path.resolve instead of require.resolve. path.resolve will look in the
user's site, which likely doesn't have the template.

First error:
==========

```
The plugin "gatsby-theme-minimal-blog" created a page with a component that doesn't exist
```

Second potential error
========

```
Error: Cannot find module 'src/templates/post.js'
```

require.resolve will need a relative path rather than a path that
looks like a node module. use `./src/templates/post.js`