[bug]: Component Shadowing
Because the component shadowing plugin [iterates over experimental
themes key without checking to see if `resolve` isn't
defined](https://github.com/gatsbyjs/gatsby/blob/43c1d3409a91fe8bbb4f07f543198da4eb11c282/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/gatsby-node.js#L14),
any user site that uses no `resolve` key in the syntax like:
`__experimentalThemes: ['my-theme']`, will run into the following
error. The fix is to use the resolve syntax always for now.

```
{
  resolve: 'my-theme',
  options: {}
}
```

```
(node:19676) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
error UNHANDLED EXCEPTION

  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

  - index.js:22 matchingThemes.themes.filter.name
    [user-site]/[gatsby]/dist/internal-plugins/webpack-theme-component-shadowing/index.js:22:84

  - Array.filter

  - index.js:22 Resolver.resolver.plugin
    [user-site]/[gatsby]/dist/internal-plugins/webpack-theme-component-shadowing/index.js:22:42

  - Resolver.js:78 options.fn
    [gatsby-starter-minimal-blog]/[enhanced-resolve]/lib/Resolver.js:78:9

  - Hook.js:154 AsyncSeriesBailHook.lazyCompileHook
    [gatsby-starter-minimal-blog]/[tapable]/lib/Hook.js:154:20

  - Resolver.js:235 Resolver.doResolve
    [gatsby-starter-minimal-blog]/[enhanced-resolve]/lib/Resolver.js:235:16
```